# Generated by Django 3.0.3 on 2021-03-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faceapp/images/staffs')),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
                ('desgination', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.StaffInfo')),
            ],
        ),
    ]
