# Generated by Django 3.0.3 on 2021-08-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='faceapp/images/staffs')),
                ('weekend', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='../static/faceapp/images/admin/defaultProfile.png', upload_to='faceapp/images/staffs')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('desgination', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('contact', models.BigIntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('dob', models.DateTimeField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('dateOfJoin', models.DateTimeField(blank=True, default=None, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('startYear', models.IntegerField(null=True)),
                ('endYear', models.IntegerField(null=True)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.TimeField()),
                ('exitTime', models.TimeField()),
                ('tolerance', models.IntegerField(null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=255)),
                ('startDate', models.DateField(auto_now=True)),
                ('endDate', models.DateField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('halfday', models.BooleanField()),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('late_time', models.IntegerField(null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
