# Generated by Django 3.0.3 on 2021-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='faceapp/images/staffs'),
            preserve_default=False,
        ),
    ]
